language: java
jdk:
  - oraclejdk8
script: sh -c "cd bwat-server && mvn test"
notifications:
  email:
    - anil.surmeli@gmail.com
    - mahmutaliozkuran@gmail.com
    - gokhan.ozgozen@gmail.com
    - ozlem.akbas@boun.edu.tr
    - sarah.beirkdar@gmail.com
    - ugurhicyilmam@gmail.com
  slack:
    rooms:
      - swe574:KDnFR0ClyhedICwgylVMFmj8#general
cache:
  directories:
    - $HOME/.m2
